//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MataFome2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Balanco
    {
        public int Id { get; set; }
        public int QuantidadeAntiga { get; set; }
        public int QuantidadeNova { get; set; }
        public string Data { get; set; }
        public string Hora { get; set; }
        public int UsuarioId { get; set; }
        public int EstoqueId { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Estoque Estoque { get; set; }
    }
}
