//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MataFome2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Venda = new HashSet<Venda>();
            this.FidelidadeCliente = new HashSet<FidelidadeCliente>();
        }
    
        public int Id { get; set; }
        public string NomeCliente { get; set; }
        public string CPF { get; set; }
        public int Telefone { get; set; }
        public string Endereco { get; set; }
        public Nullable<int> Numero { get; set; }
        public string Bairro { get; set; }
        public string Municipio { get; set; }
        public string CEP { get; set; }
        public string Observacao { get; set; }
        public double TaxaEntrega { get; set; }
        public int PontosFidelidade { get; set; }
        public Nullable<int> ContadorVendas { get; set; }
        public string Complemento { get; set; }
        public Nullable<double> TotalGasto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Venda> Venda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FidelidadeCliente> FidelidadeCliente { get; set; }
    }
}
