//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MataFome2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LanchoneteEntityContainer : DbContext
    {
        public LanchoneteEntityContainer()
            : base("name=LanchoneteEntityContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<Venda> Venda { get; set; }
        public virtual DbSet<Produto> Produtos { get; set; }
        public virtual DbSet<ProdutoVenda> ProdutoVendas { get; set; }
        public virtual DbSet<FormaPagamento> FormaPagamentos { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<OperadorCaixa> OperadorCaixas { get; set; }
        public virtual DbSet<Estoque> Estoques { get; set; }
        public virtual DbSet<Balanco> Balancos { get; set; }
        public virtual DbSet<ProdutosFidelidade> ProdutosFidelidades { get; set; }
        public virtual DbSet<FidelidadeCliente> FidelidadeClienteSet { get; set; }
        public virtual DbSet<PagamentoVenda> PagamentoVenda { get; set; }
        public virtual DbSet<Motoqueiros> Motoqueiros { get; set; }
        public virtual DbSet<Saidas> Saidas { get; set; }
        public virtual DbSet<Table_1> Table_1 { get; set; }
    }
}
