//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MataFome2
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagamentoVenda
    {
        public int Id { get; set; }
        public string Descricao { get; set; }
        public int VendaId { get; set; }
        public int FormaPagamentoId { get; set; }
    
        public virtual FormaPagamento FormaPagamentos { get; set; }
        public virtual Venda Venda { get; set; }
    }
}
