//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MataFome2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Venda()
        {
            this.ProdutoVenda = new HashSet<ProdutoVenda>();
            this.PagamentoVenda = new HashSet<PagamentoVenda>();
        }
    
        public int Id { get; set; }
        public double Total { get; set; }
        public string DataVenda { get; set; }
        public string Situacao { get; set; }
        public int ClienteId { get; set; }
        public Nullable<int> FormaPagamentoId { get; set; }
        public string ObservacaoVenda { get; set; }
        public string Status { get; set; }
        public int OperadorCaixaId { get; set; }
        public System.DateTime DataComparadora { get; set; }
        public double TaxaEntregaVenda { get; set; }
        public Nullable<int> MotoqueiroId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProdutoVenda> ProdutoVenda { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual OperadorCaixa OperadorCaixa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagamentoVenda> PagamentoVenda { get; set; }
        public virtual Motoqueiros Motoqueiros { get; set; }
        public virtual Table_1 Table_1 { get; set; }
    }
}
